### PR TITLE
Actions map

### PR DESCRIPTION
**Pull request by cscovino**
Expose BulkDelete action in ActionsMap so we can modify the default action in global manner, as we can do with actions like edit, show, new and so on.

### CODE REVIEW

**Comment by dziraf** [comment]
Could you rebase your branch to our `beta` branch?

**Comment by cscovino** [comment]
@dziraf It is ok now?

**Comment by dziraf** [comment]
Yes, could you also rebase this one: https://github.com/SoftwareBrothers/admin-bro/pull/793

I see your branches depend on one another but I want to merge PRs one by one. These changes will be released in `beta` channel after merging (`admin-bro@beta`)

**Comment by cscovino** [comment]
ok, sorry for that.

**Review by dziraf — APPROVED** [review]

**Comment by dziraf** [comment]
No problem, sorry for the delay and thanks for contributing

**Pull request merged**
