### PR TITLE
fix: show date (only) format without time

### PR DESCRIPTION
**Pull request by leibowitz**
Pass the `property.type` (as `propertyType` prop) to the `DatePicker` component to show the relevant format for date (only) types

### CODE REVIEW

**Comment by ungurnicoleta** [comment]
Hi! I still have problems with the date/time. Whenever I save time, it will show me a time 3 hours ahead than the one I choose.

**Comment by wojtek-krysiak** [comment]
can you create an issue regarding that?

**Comment by ungurnicoleta** [comment]
I've created an issue.

https://github.com/SoftwareBrothers/admin-bro/issues/586

**Comment by ungurnicoleta** [comment]
https://github.com/SoftwareBrothers/admin-bro/issues/586

**Pull request merged**
